services:
  aiapi:
    image: ghcr.io/tna76874/binaryaiapi:latest
    ports:
      - "5000:5000"
    container_name: aiapi
    environment:
      - CNN_API_KEY=test
      - CNN_MODEL_PATH=/app/data/model.keras
    volumes:
      - ./data:/app/data
