services:
  aiapi:
    image: ghcr.io/tna76874/binaryaiapi:latest
    ports:
      - "5500:5000"
    container_name: aiapi
    environment:
      - CNN_API_KEY=test
      - CNN_MODEL_PATH=/app/data/model.keras
      - CNN_MODEL_THRESHOLD=0.2
      - BLUR_THRESHOLD=40
    volumes:
      - ./data:/app/data
